# NumPy + Pandas Tutorial

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(42)

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 2.0.2
Pandas version: 2.2.2

# Part 1 — NumPy

## 1.1 Creating Arrays

In [ ]:
# From a Python list
a = np.array([1, 2, 3, 4, 5])
print("1D array:", a)

# 2D array (matrix) from nested lists
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print("2D array:\n", b)

# Common generators
print("\nzeros(3):", np.zeros(3))
print("ones((2,3)):\n", np.ones((2, 3)))
print("arange(0,10,2):", np.arange(0, 10, 2))
print("linspace(0,1,5):", np.linspace(0, 1, 5))

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]

zeros(3): [0. 0. 0.]
ones((2,3)):
 [[1. 1. 1.]
 [1. 1. 1.]]
arange(0,10,2): [0 2 4 6 8]
linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]

In [ ]:
# Array attributes
print("shape:", b.shape)   # (rows, cols)
print("ndim:", b.ndim)     # number of dimensions
print("size:", b.size)     # total number of elements
print("dtype:", b.dtype)   # data type of the elements

shape: (2, 3)
ndim: 2
size: 6
dtype: int64

## 1.2 Indexing & Slicing

In [ ]:
m = np.array([[10, 11, 12, 13],
              [14, 15, 16, 17],
              [18, 19, 20, 21]])

print("Element at row 1, col 2:", m[1, 2])
print("Entire row 0:", m[0, :])
print("Entire column 1:", m[:, 1])
print("Sub-matrix (rows 0-1, cols 1-2):\n", m[0:2, 1:3])

# Boolean indexing
print("\nElements > 15:", m[m > 15])

Element at row 1, col 2: 16
Entire row 0: [10 11 12 13]
Entire column 1: [11 15 19]
Sub-matrix (rows 0-1, cols 1-2):
 [[11 12]
 [15 16]]

Elements > 15: [16 17 18 19 20 21]

## 1.3 Reshaping & Transpose

In [ ]:
arr = np.arange(12)
print("Original:", arr)

reshaped = arr.reshape(3, 4)
print("\nReshaped to (3,4):\n", reshaped)

auto_reshaped = arr.reshape(4, -1)  # infer the second dimension
print("\nReshaped (4,-1):\n", auto_reshaped)

print("\nTranspose of (3,4):\n", reshaped.T)
print("Transpose shape:", reshaped.T.shape)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to (3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped (4,-1):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Transpose of (3,4):
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Transpose shape: (4, 3)

## 1.4 Arithmetic

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print("x + y :", x + y)
print("x * y :", x * y)
print("x ** 2:", x ** 2)
print("y / x :", y / x)

x + y : [11 22 33]
x * y : [10 40 90]
x ** 2: [1 4 9]
y / x : [10. 10. 10.]

## 1.5 Aggregations & `axis`

Aggregations like `sum`, `mean`, `std` can be applied over the whole array or along a specific axis.

```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]

axis=0 → collapse DOWN the rows → one result per COLUMN → [12, 15, 18]
axis=1 → collapse ACROSS the columns → one result per ROW → [6, 15, 24]
```

In [ ]:
data = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Sum (all):", data.sum())
print("Sum (axis=0, per column):", data.sum(axis=0))
print("Sum (axis=1, per row):", data.sum(axis=1))
print("Mean (axis=0):", data.mean(axis=0))
print("Std  (axis=0):", data.std(axis=0))

Sum (all): 45
Sum (axis=0, per column): [12 15 18]
Sum (axis=1, per row): [ 6 15 24]
Mean (axis=0): [4. 5. 6.]
Std  (axis=0): [2.44948974 2.44948974 2.44948974]

## 1.6 Dot Products & Matrix Multiplication

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Vector dot product - two ways
print("np.dot(x, y):", np.dot(x, y))
print("x @ y       :", x @ y)

np.dot(x, y): 32
x @ y       : 32

In [ ]:
# Matrix-vector multiplication: X has shape (n_samples, n_features),
# w is a weight vector with shape (n_features,)
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])
w = np.array([10, 20])

predictions = X @ w
print("X shape:", X.shape, " w shape:", w.shape)
print("X @ w   :", predictions, " -> shape", predictions.shape)
# (3, 2) @ (2,) -> (3,)  one prediction per sample

X shape: (3, 2)  w shape: (2,)
X @ w   : [ 50 110 170]  -> shape (3,)

In [ ]:
A = np.array([[2, 1],
              [1, 3]], dtype=float)
B = np.array([[1, 0],
              [0, 1]], dtype=float)

print("A @ B (matrix multiplication):\n", A @ B)
print("\nA.T (transpose):\n", A.T)

A @ B (matrix multiplication):
 [[2. 1.]
 [1. 3.]]

A.T (transpose):
 [[2. 1.]
 [1. 3.]]

## 1.7 Linear-Algebra Essentials

* `np.linalg.norm` — vector length / magnitude, used for regularization and distances
* `np.linalg.solve(A, b)` — solve `Ax = b`
* `np.linalg.inv` — matrix inverse
* `np.linalg.eig` — eigenvalues/eigenvectors

In [ ]:
print("Norm of x:", np.linalg.norm(x))

b_vec = np.array([5, 10])
x_sol = np.linalg.solve(A, b_vec)
print("\nSolving A x = b -> x =", x_sol)

print("\nInverse of A:\n", np.linalg.inv(A))

eigvals, eigvecs = np.linalg.eig(A)
print("\nEigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

Norm of x: 3.7416573867739413

Solving A x = b -> x = [1. 3.]

Inverse of A:
 [[ 0.6 -0.2]
 [-0.2  0.4]]

Eigenvalues: [1.38196601 3.61803399]
Eigenvectors:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]

## 1.8 Random Numbers

In [ ]:
rng = np.random.default_rng(42)

print("Uniform [0,1):", rng.random(5))
print("Standard normal:", rng.standard_normal(5))
print("Random ints [0,10):", rng.integers(0, 10, size=5))

Uniform [0,1): [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Standard normal: [-1.30217951  0.1278404  -0.31624259 -0.01680116 -0.85304393]
Random ints [0,10): [5 3 1 9 7]

## 1.9 Stacking & Concatenating

In [ ]:
p = np.array([1, 2, 3])
q = np.array([4, 5, 6])

print("vstack (stack rows):\n", np.vstack([p, q]))
print("\nhstack (stack side by side):", np.hstack([p, q]))
print("\nconcatenate along axis=0:\n", np.concatenate([p, q]))

vstack (stack rows):
 [[1 2 3]
 [4 5 6]]

hstack (stack side by side): [1 2 3 4 5 6]

concatenate along axis=0:
 [1 2 3 4 5 6]

## 1.10 Vectorization: NumPy vs Python for loop

In [ ]:
import time

n = 2_000_000
big = np.random.rand(n)

start = time.time()
total = 0.0
for val in big:
    total += val ** 2
loop_time = time.time() - start

start = time.time()
total_vec = np.sum(big ** 2)
vec_time = time.time() - start

print(f"Loop:       {loop_time:.4f}s")
print(f"Vectorized: {vec_time:.4f}s")
print(f"Speedup: ~{loop_time / vec_time:.0f}x")

Loop:       0.7697s
Vectorized: 0.0113s
Speedup: ~68x

# Part 2 — Pandas

`Series` (1D) and `DataFrame` (2D)

## 2.1 Series and DataFrames

In [ ]:
# Series: a single labeled column
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'], name='marks')
print(s)
print("\nAccess by label:", s['b'])

a    10
b    20
c    30
d    40
Name: marks, dtype: int64

Access by label: 20

In [ ]:
# DataFrame: dict of columns
df = pd.DataFrame({
    'student': ['Aarav', 'Diya', 'Kabir', 'Meera', 'Rohan'],
    'age':      [21, 22, 20, 23, 21],
    'branch':   ['CSE', 'CSAI', 'CSE', 'ECE', 'CSAI'],
    'cgpa':     [8.9, 9.2, 7.8, None, 8.5],
})
df

  student  age branch  cgpa
0   Aarav   21    CSE   8.9
1    Diya   22   CSAI   9.2
2   Kabir   20    CSE   7.8
3   Meera   23    ECE   NaN
4   Rohan   21   CSAI   8.5

## 2.2 Inspecting a DataFrame

In [ ]:
print(df.shape)      # (rows, cols)
print(df.columns.tolist())
print(df.dtypes)

(5, 4)
['student', 'age', 'branch', 'cgpa']
student     object
age          int64
branch      object
cgpa       float64
dtype: object

In [ ]:
df.head(3)   # first 3 rows

  student  age branch  cgpa
0   Aarav   21    CSE   8.9
1    Diya   22   CSAI   9.2
2   Kabir   20    CSE   7.8

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   student  5 non-null      object
 1   age      5 non-null      int64
 2   branch   5 non-null      object
 3   cgpa     4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [ ]:
df.describe()   # summary stats for numeric columns

             age     cgpa
count   5.000000  4.00000
mean   21.400000  8.60000
std     1.140175  0.60553
min    20.000000  7.80000
25%    21.000000  8.32500
50%    21.000000  8.70000
75%    22.000000  8.97500
max    23.000000  9.20000

## 2.3 Indexing: `loc`, `iloc`, Boolean Filtering`

* `.loc[]` — label-based indexing
* `.iloc[]` — position-based (integer) indexing
* Boolean masks — filter rows matching a condition (used constantly)

In [ ]:
print("Row with label 2 via .loc:\n", df.loc[2])
print("\nFirst 2 rows, first 2 cols via .iloc:\n", df.iloc[0:2, 0:2])

# Boolean filtering
csai_students = df[df['branch'] == 'CSAI']
print("\nCSAI students:\n", csai_students)

Row with label 2 via .loc:
 student    Kabir
age           20
branch       CSE
cgpa         7.8
Name: 2, dtype: object

First 2 rows, first 2 cols via .iloc:
   student  age
0   Aarav   21
1    Diya   22

CSAI students:
   student  age branch  cgpa
1    Diya   22   CSAI   9.2
4   Rohan   21   CSAI   8.5

## 2.4 Handling Missing Data

Real datasets almost always have missing values. `isna()`, `dropna()`, and `fillna()`

In [ ]:
print("Missing values per column:\n", df.isna().sum())

# Drop rows with any missing value
print("\nAfter dropna():\n", df.dropna())

# Fill missing values (e.g. with the column mean)
df_filled = df.copy()
df_filled['cgpa'] = df_filled['cgpa'].fillna(df_filled['cgpa'].mean())
df_filled

Missing values per column:
 student    0
age        0
branch     0
cgpa       1
dtype: int64

After dropna():
   student  age branch  cgpa
0   Aarav   21    CSE   8.9
1    Diya   22   CSAI   9.2
2   Kabir   20    CSE   7.8
4   Rohan   21   CSAI   8.5

  student  age branch  cgpa
0   Aarav   21    CSE   8.9
1    Diya   22   CSAI   9.2
2   Kabir   20    CSE   7.8
3   Meera   23    ECE   8.6
4   Rohan   21   CSAI   8.5

## 2.5 Understanding Categorical Columns
`value_counts`, `unique`, `nunique`

In [ ]:
print("Unique branches:", df_filled['branch'].unique())
print("Number of unique branches:", df_filled['branch'].nunique())
print("\nCounts per branch:\n", df_filled['branch'].value_counts())
print("\nProportion per branch:\n", df_filled['branch'].value_counts(normalize=True))

Unique branches: ['CSE' 'CSAI' 'ECE']
Number of unique branches: 3

Counts per branch:
 branch
CSE     2
CSAI    2
ECE     1
Name: count, dtype: int64

Proportion per branch:
 branch
CSE     0.4
CSAI    0.4
ECE     0.2
Name: proportion, dtype: float64

## 2.6 Merging & Concatenating

In [ ]:
results = pd.DataFrame({
    'student': ['Aarav', 'Diya', 'Kabir', 'Meera', 'Rohan'],
    'has_ml': ['Yes', 'Yes', 'No', 'Yes', 'No']
})

merged = pd.merge(df, results, on='student', how='left')
merged

  student  age branch  cgpa has_ml
0   Aarav   21    CSE   8.9    Yes
1    Diya   22   CSAI   9.2    Yes
2   Kabir   20    CSE   7.8     No
3   Meera   23    ECE   NaN    Yes
4   Rohan   21   CSAI   8.5     No